name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    # - name: Cache go dependencies
    #   uses: actions/cache@v2
    #   env:
    #     cache-name: cache-go-modules
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Get dependencies
      run: |
        pwd
        env
        go get -v -t -d ./...
        wget https://www.foundationdb.org/downloads/6.2.25/ubuntu/installers/foundationdb-clients_6.2.25-1_amd64.deb
        sudo apt install ./foundationdb-clients_6.2.25-1_amd64.deb

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -cover .
